<?php

use Illuminate\Database\Seeder;
use App\Models\Ramadan;
class RamadansTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $array = [
            
            // BD-13: dhaka
            [
                'date' => "2018-05-16",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-13",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-13",
            ],

            // Barisal
            [
                'date' => "2018-05-16",
                'sehrTime' => "3:55",
                'fajrTime' => "",
                'iftarTime' => "6:32",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:55",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:53",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-06",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-06",
            ],


            //Chittagong
            [
                'date' => "2018-05-16",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:26",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:26",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:27",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:27",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:28",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:28",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:29",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:29",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:29",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:30",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:30",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:31",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:31",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:32",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:32",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-10",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-10",
            ],


            //Khulna

            [
                'date' => "2018-05-16",
                'sehrTime' => "3:58",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:58",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:57",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:56",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:56",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:55",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:55",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:53",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:53",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-27",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:48",
                'areaCode' => "BD-27",
            ],


            //Rajshahi

            [
                'date' => "2018-05-16",
                'sehrTime' => "3:58",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:57",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:57",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:56",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:55",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:55",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:54",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:53",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:53",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:48",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:48",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:48",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:49",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:49",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:50",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:50",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:51",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:51",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:52",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:52",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:52",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:53",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:53",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:54",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:54",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:54",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:55",
                'areaCode' => "BD-54",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:55",
                'areaCode' => "BD-54",
            ],

            //Rangpur

             [
                'date' => "2018-05-16",
                'sehrTime' => "3:52",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:51",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:50",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:49",
                'fajrTime' => "",
                'iftarTime' => "6:44",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:48",
                'fajrTime' => "",
                'iftarTime' => "6:45",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:47",
                'fajrTime' => "",
                'iftarTime' => "6:46",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:46",
                'fajrTime' => "",
                'iftarTime' => "6:47",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:48",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:45",
                'fajrTime' => "",
                'iftarTime' => "6:48",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:49",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:44",
                'fajrTime' => "",
                'iftarTime' => "6:49",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:50",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:50",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:50",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:51",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:51",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:51",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:52",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:53",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:53",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:54",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:54",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:54",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:55",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:55",
                'areaCode' => "BD-55",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:55",
                'areaCode' => "BD-55",
            ],


            //Sylhet

            [
                'date' => "2018-05-16",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:30",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-17",
                'sehrTime' => "3:43",
                'fajrTime' => "",
                'iftarTime' => "6:30",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-18",
                'sehrTime' => "3:42",
                'fajrTime' => "",
                'iftarTime' => "6:31",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-19",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:31",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-20",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:32",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-21",
                'sehrTime' => "3:40",
                'fajrTime' => "",
                'iftarTime' => "6:32",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-22",
                'sehrTime' => "3:40",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-23",
                'sehrTime' => "3:39",
                'fajrTime' => "",
                'iftarTime' => "6:33",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-24",
                'sehrTime' => "3:39",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-25",
                'sehrTime' => "3:38",
                'fajrTime' => "",
                'iftarTime' => "6:34",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-26",
                'sehrTime' => "3:38",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-27",
                'sehrTime' => "3:37",
                'fajrTime' => "",
                'iftarTime' => "6:35",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-28",
                'sehrTime' => "3:37",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-29",
                'sehrTime' => "3:36",
                'fajrTime' => "",
                'iftarTime' => "6:36",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-30",
                'sehrTime' => "3:36",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-05-31",
                'sehrTime' => "3:36",
                'fajrTime' => "",
                'iftarTime' => "6:37",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-01",
                'sehrTime' => "3:35",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-02",
                'sehrTime' => "3:35",
                'fajrTime' => "",
                'iftarTime' => "6:38",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-03",
                'sehrTime' => "3:35",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-04",
                'sehrTime' => "3:35",
                'fajrTime' => "",
                'iftarTime' => "6:39",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-05",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-06",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-07",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:40",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-08",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-09",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:41",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-10",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-11",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-12",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:42",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-13",
                'sehrTime' => "3:34",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-60",
            ], [
                'date' => "2018-06-14",
                'sehrTime' => "3:41",
                'fajrTime' => "",
                'iftarTime' => "6:43",
                'areaCode' => "BD-60",
            ],


                //Mymensingh 

                [
                    'date' => "2018-05-16",
                    'sehrTime' => "3:50",
                    'fajrTime' => "",
                    'iftarTime' => "6:36",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-17",
                    'sehrTime' => "3:49",
                    'fajrTime' => "",
                    'iftarTime' => "6:36",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-18",
                    'sehrTime' => "3:48",
                    'fajrTime' => "",
                    'iftarTime' => "6:37",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-19",
                    'sehrTime' => "3:48",
                    'fajrTime' => "",
                    'iftarTime' => "6:37",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-20",
                    'sehrTime' => "3:47",
                    'fajrTime' => "",
                    'iftarTime' => "6:38",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-21",
                    'sehrTime' => "3:47",
                    'fajrTime' => "",
                    'iftarTime' => "6:38",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-22",
                    'sehrTime' => "3:46",
                    'fajrTime' => "",
                    'iftarTime' => "6:39",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-23",
                    'sehrTime' => "3:45",
                    'fajrTime' => "",
                    'iftarTime' => "6:39",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-24",
                    'sehrTime' => "3:45",
                    'fajrTime' => "",
                    'iftarTime' => "6:40",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-25",
                    'sehrTime' => "3:44",
                    'fajrTime' => "",
                    'iftarTime' => "6:40",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-26",
                    'sehrTime' => "3:44",
                    'fajrTime' => "",
                    'iftarTime' => "6:41",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-27",
                    'sehrTime' => "3:44",
                    'fajrTime' => "",
                    'iftarTime' => "6:41",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-28",
                    'sehrTime' => "3:43",
                    'fajrTime' => "",
                    'iftarTime' => "6:42",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-29",
                    'sehrTime' => "3:43",
                    'fajrTime' => "",
                    'iftarTime' => "6:42",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-30",
                    'sehrTime' => "3:42",
                    'fajrTime' => "",
                    'iftarTime' => "6:42",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-05-31",
                    'sehrTime' => "3:42",
                    'fajrTime' => "",
                    'iftarTime' => "6:43",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-01",
                    'sehrTime' => "3:42",
                    'fajrTime' => "",
                    'iftarTime' => "6:43",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-02",
                    'sehrTime' => "3:41",
                    'fajrTime' => "",
                    'iftarTime' => "6:44",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-03",
                    'sehrTime' => "3:41",
                    'fajrTime' => "",
                    'iftarTime' => "6:44",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-04",
                    'sehrTime' => "3:41",
                    'fajrTime' => "",
                    'iftarTime' => "6:45",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-05",
                    'sehrTime' => "3:41",
                    'fajrTime' => "",
                    'iftarTime' => "6:45",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-06",
                    'sehrTime' => "3:41",
                    'fajrTime' => "",
                    'iftarTime' => "6:46",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-07",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:46",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-08",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:46",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-09",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:47",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-10",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:47",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-11",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:47",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-12",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:48",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-13",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:48",
                    'areaCode' => "BD-34",
                ], [
                    'date' => "2018-06-14",
                    'sehrTime' => "3:40",
                    'fajrTime' => "",
                    'iftarTime' => "6:49",
                    'areaCode' => "BD-34",
                ],
    


         ];
        // Publisher::delete();
         foreach ($array as $key => $value) {
            Ramadan::create($value);
         }
    }
}
