INSERT INTO dayflags (flag,name) 
values 
(1,"Holiday")
,(2,"National day")
,(3,"Holiday & National Day")
,(4,"International Day")
,(5,"Holiday & International Day")
,(6,"National & International Day")
,(7,"Holiday, National Day & International Day")
,(8,"Birth day")
,(16,"Birth day")
