
select * from daydates where dayid is NULL;

delete  from  days;

INSERT INTO days(dayKey,dayCategory,dayFlag,title) 
values
("21-FEB","GNL",3,"শহীদ দিবস ও আন্তর্জাতিক মাতৃভাষা দিবস")	
,("17-MAR","GNL",3,"জাতির জনক বঙ্গবন্ধু শেখ মজিবুর রাহমান এর জন্ম দিন")
,("26-MAR","GNL",3,"স্বাধীনতা ও জাতীয় দিবস")
,("BN-NOBO","GNL",3,"বাংলা নববর্ষ")
,("MAY-DAY","GNL",5,"মে দিবস")
,("B-PURNIMA","BDO",1,"বুদ্ধ পূর্ণিমা")
,("EID-UL-FITAR","MLM",1,"ঈদ-উল-ফিতর")
,("SOBE-KADOR","MLM",1,"শবে-কদর")
,("JUMATUL-BIDAH","MLM",1,"জুমা-তুল-বিদা")
,("SOBE-BORAT","MLM",1,"শবে-বরাত")
,("ASHURA","MLM",1,"পবিত্র  আশুরা")
,("DURGA-PUGA-10TH","HDU",1,"শারদীয় দূর্গাপূজা (বিজয়া দশমী)")
,("EID-UL-ADHA","MLM",1,"ঈদ-উল-আযহা")
,("JANMO-ASTOMI","HDU",1,"শুভ জন্মাষ্টমী")
,("15-AUG","GNL",3,"জাতীয় শোক দিবস")
,("BORO-DIN","CRN",1,"যীশু খ্রীষ্টের জন্মদিন (বড়দিন)")
,("16-DEC","GNL",3,"বিজয় দিবস")
,("EID-E-MILADUN","MLM",1,"ঈদ-ই-মিলাদুন্নবী (সাঃ)")
,("SOBE-MIRAZ","MLM",1,"শব-ই-মিরাজ")
,("FATEHA-E-YAJDAHUM","MLM",1,"ফাতেহা-ই-ইয়াজদাহম")
,("AKHERI-CAHAR-SOMBA","MLM",1,"আখেরী চাহার সোম্বা")
,("SOROSOTI-PUJA","HDU",1,"শ্রী শ্রী সরস্বতী পূজা")
,("SHIBRATRI-BROTO","HDU",1,"শ্রী শ্রী শিবরাত্রী ব্রত")
,("DOL-JATRA","HDU",1,"শুভ দোল যাত্রা")
,("THAKUR-ABIRVAB","HDU",1,"শ্রী শ্রী হরিচাঁদ ঠাকুরের আবির্ভাব")	
,("MOHALYA","HDU",1,"শুভ মহালয়া")
,("DURGA-PUGA-09TH","HDU",1,"শ্রী শ্রী দূর্গাপূজা (মহানবমী)")
,("LAKSHMI-PUJA","HDU",1,"শ্রী শ্রী লক্ষ্মী পূজা")
,("SHAMA-PUJA","HDU",1,"শ্রী শ্রী শ্যামা পূজা")
,("EN-NOBO","CRN",1,"ইংরেজী নববর্ষ	")
,("VOSMO-WED","CRN",1,"ভস্ম বুধবার")
,("PUNNO-THR","CRN",1,"পূণ্য বৃহস্পতিবার")
,("PUNNO-SAT","CRN",1,"পূণ্য শনিবার")
,("PUNNO-FRI","CRN",1,"পূণ্য শুক্রবার")
,("ESTAR-SUN","CRN",1,"ইস্টার সানডে")
,("M-PURNIMA","BDO",1,"মাঘী পূর্ণিমা")
,("CHYTRO-SOKGKRANTI","BDO",1,"চৈত্র সংক্রান্তি")
,("ASHARI-PURNIMA","BDO",1,"আষাঢ়ী পূর্ণিমা")
,("MODHU-PURNIMA","BDO",1,"মধু পূর্ণিমা (ভাদ্র পূর্ণিমা)")
,("PROBARONA-PURNIMA","BDO",1,"প্রবারণা পূর্ণিমা (আশ্বিনী পূর্ণিমা)")
,("OTHR","	OHR",1,"বৈসাবি ও পার্বত্য চট্টগ্রামের অন্যান্য ক্ষুদ্র নৃ-গোষ্ঠী সমূহের অনুরূপ সামাজিক উৎসব")
,("DURGA-PUGA-08TH","HDU",1,"শ্রী শ্রী দূর্গাপূজা (মহাষ্টমী)");